package com.martmists.kmine.network.packets

import kotlin.reflect.*

enum class PacketType(val state: ProtocolState, val serverbound: Boolean, val value: Int) {
    // Handshake packet types
    HANDSHAKE(ProtocolState.HANDSHAKE, true, 0),
//    LEGACY_SERVER_LIST_PING(ProtocolState.HANDSHAKE, true, 0xFE),

    // Status packet types
    STATUS_RESPONSE(ProtocolState.STATUS, false, 0),
    STATUS_PONG(ProtocolState.STATUS, false, 1),
    STATUS_REQUEST(ProtocolState.STATUS, true, 0),
    STATUS_PING(ProtocolState.STATUS, true, 1),

    // Login packet types
    LOGIN_DISCONNECT(ProtocolState.LOGIN, false, 0),
    LOGIN_ENCRYPT_REQUEST(ProtocolState.LOGIN, false, 1),
    LOGIN_SUCCESS(ProtocolState.LOGIN, false, 2),
    LOGIN_SET_COMPRESSION(ProtocolState.LOGIN, false, 3),
    LOGIN_PLUGIN_REQUEST(ProtocolState.LOGIN, false, 4),
    LOGIN_START(ProtocolState.LOGIN, true, 0),
    LOGIN_ENCRYPT_RESPONSE(ProtocolState.LOGIN, true, 1),
    LOGIN_PLUGIN_RESPONSE(ProtocolState.LOGIN, true, 2),

    // Play packet types
    PLAY_SPAWN_ENTITY(ProtocolState.PLAY, false, 0x0),
    PLAY_SPAWN_EXP(ProtocolState.PLAY, false, 0x1),
    PLAY_SPAWN_LIVING(ProtocolState.PLAY, false, 0x2),
    PLAY_SPAWN_PAINTING(ProtocolState.PLAY, false, 0x3),
    PLAY_SPAWN_PLAYER(ProtocolState.PLAY, false, 0x4),
    PLAY_SKULK_SIGNAL(ProtocolState.PLAY, false, 0x5),
    PLAY_ENTITY_ANIMATION(ProtocolState.PLAY, false, 0x6),
    PLAY_STATISTICS(ProtocolState.PLAY, false, 0x7),
    PLAY_ACK_DIGGING(ProtocolState.PLAY, false, 0x8),
    PLAY_BLOCK_BREAK_ANIMATION(ProtocolState.PLAY, false, 0x9),
    PLAY_BLOCK_ENTITY_UPDATE(ProtocolState.PLAY, false, 0xa),
    PLAY_BLOCK_ACTION(ProtocolState.PLAY, false, 0xb),
    PLAY_BLOCK_CHANGE(ProtocolState.PLAY, false, 0xc),
    PLAY_BOSS_BAR(ProtocolState.PLAY, false, 0xd),
    PLAY_SERVER_DIFFICULTY(ProtocolState.PLAY, false, 0xe),
    PLAY_CHAT_MESSAGE(ProtocolState.PLAY, false, 0xf),
    PLAY_CLEAR_TITLES(ProtocolState.PLAY, false, 0x10),
    PLAY_TAB_COMPLETE(ProtocolState.PLAY, false, 0x11),
    PLAY_DECLARE_COMMANDS(ProtocolState.PLAY, false, 0x12),
    PLAY_CLOSE_WINDOW(ProtocolState.PLAY, false, 0x13),
    PLAY_WINDOW_ITEMS(ProtocolState.PLAY, false, 0x14),
    PLAY_WINDOW_PROPERTY(ProtocolState.PLAY, false, 0x15),
    PLAY_SET_SLOT(ProtocolState.PLAY, false, 0x16),
    PLAY_SET_COOLDOWN(ProtocolState.PLAY, false, 0x17),
    PLAY_PLUGIN_MESSAGE(ProtocolState.PLAY, false, 0x18),
    PLAY_NAMED_SOUNDFX(ProtocolState.PLAY, false, 0x19),
    PLAY_DISCONNECT(ProtocolState.PLAY, false, 0x1a),
    PLAY_ENTITY_STATUS(ProtocolState.PLAY, false, 0x1b),
    PLAY_EXPLOSION(ProtocolState.PLAY, false, 0x1c),
    PLAY_UNLOAD_CHUNK(ProtocolState.PLAY, false, 0x1d),
    PLAY_CHANGE_GAME_STATE(ProtocolState.PLAY, false, 0x1e),
    PLAY_OPEN_HORSE_GUI(ProtocolState.PLAY, false, 0x1f),
    PLAY_INITIALIZE_WORLD_BORDER(ProtocolState.PLAY, false, 0x20),
    PLAY_KEEP_ALIVE(ProtocolState.PLAY, false, 0x21),
    PLAY_CHUNK_LIGHT_UPDATE(ProtocolState.PLAY, false, 0x22),
    PLAY_EFFECT(ProtocolState.PLAY, false, 0x23),
    PLAY_PARTICLE(ProtocolState.PLAY, false, 0x24),
    PLAY_UPDATE_LIGHT(ProtocolState.PLAY, false, 0x25),
    PLAY_JOIN_GAME(ProtocolState.PLAY, false, 0x26),
    PLAY_MAP_DATA(ProtocolState.PLAY, false, 0x27),
    PLAY_TRADE_LIST(ProtocolState.PLAY, false, 0x28),
    PLAY_ENTITY_POSITION(ProtocolState.PLAY, false, 0x29),
    PLAY_ENTITY_POSITION_ROTATION(ProtocolState.PLAY, false, 0x2a),
    PLAY_ENTITY_ROTATION(ProtocolState.PLAY, false, 0x2b),
    PLAY_VEHICLE_MOVE(ProtocolState.PLAY, false, 0x2c),
    PLAY_OPEN_BOOK(ProtocolState.PLAY, false, 0x2d),
    PLAY_OPEN_WINDOW(ProtocolState.PLAY, false, 0x2e),
    PLAY_OPEN_SIGN_EDITOR(ProtocolState.PLAY, false, 0x2f),
    PLAY_PING(ProtocolState.PLAY, false, 0x30),
    PLAY_CRAFT_RECIPE_RESPONSE(ProtocolState.PLAY, false, 0x31),
    PLAY_PLAYER_ABILITIES(ProtocolState.PLAY, false, 0x32),
    PLAY_END_COMBAT_EVENT(ProtocolState.PLAY, false, 0x33),
    PLAY_ENTER_COMBAT_EVENT(ProtocolState.PLAY, false, 0x34),
    PLAY_DEATH_COMBAT_EVENT(ProtocolState.PLAY, false, 0x35),
    PLAY_PLAYER_INFO(ProtocolState.PLAY, false, 0x36),
    PLAY_FACE_PLAYER(ProtocolState.PLAY, false, 0x37),
    PLAY_PLAYER_POSITION_AND_LOOK(ProtocolState.PLAY, false, 0x38),
    PLAY_UNLOCK_RECIPES(ProtocolState.PLAY, false, 0x39),
    PLAY_DESTROY_ENTITIES(ProtocolState.PLAY, false, 0x3a),
    PLAY_REMOVE_ENTITY_EFFECT(ProtocolState.PLAY, false, 0x3b),
    PLAY_RESOURCE_PACK_SEND(ProtocolState.PLAY, false, 0x3c),
    PLAY_RESPAWN(ProtocolState.PLAY, false, 0x3d),
    PLAY_ENTITY_HEAD_LOOK(ProtocolState.PLAY, false, 0x3e),
    PLAY_MULTI_BLOCK_CHANGE(ProtocolState.PLAY, false, 0x3f),
    PLAY_SELECT_ADVANCEMENT_TAB(ProtocolState.PLAY, false, 0x40),
    PLAY_ACTION_BAR(ProtocolState.PLAY, false, 0x41),
    PLAY_WORLD_BORDER_CENTER(ProtocolState.PLAY, false, 0x42),
    PLAY_WORLD_BORDER_LERP_SIZE(ProtocolState.PLAY, false, 0x43),
    PLAY_WORLD_BORDER_SIZE(ProtocolState.PLAY, false, 0x44),
    PLAY_WORLD_BORDER_WARNING_DELAY(ProtocolState.PLAY, false, 0x45),
    PLAY_WORLD_BORDER_WARNING_REACH(ProtocolState.PLAY, false, 0x46),
    PLAY_CAMERA(ProtocolState.PLAY, false, 0x47),
    PLAY_HELD_ITEM_CHANGE(ProtocolState.PLAY, false, 0x48),
    PLAY_UPDATE_VIEW_POSITION(ProtocolState.PLAY, false, 0x49),
    PLAY_UPDATE_VIEW_DISTANCE(ProtocolState.PLAY, false, 0x4a),
    PLAY_SPAWN_POSITION(ProtocolState.PLAY, false, 0x4b),
    PLAY_DISPLAY_SCOREBOARD(ProtocolState.PLAY, false, 0x4c),
    PLAY_ENTITY_METADATA(ProtocolState.PLAY, false, 0x4d),
    PLAY_ATTACH_ENTITY(ProtocolState.PLAY, false, 0x4e),
    PLAY_ENTITY_VELOCITY(ProtocolState.PLAY, false, 0x4f),
    PLAY_ENTITY_EQUIPMENT(ProtocolState.PLAY, false, 0x50),
    PLAY_SET_EXPERIENCE(ProtocolState.PLAY, false, 0x51),
    PLAY_UPDATE_HEALTH(ProtocolState.PLAY, false, 0x52),
    PLAY_SCOREBOARD_OBJECTIVE(ProtocolState.PLAY, false, 0x53),
    PLAY_SET_PASSENGERS(ProtocolState.PLAY, false, 0x54),
    PLAY_TEAMS(ProtocolState.PLAY, false, 0x55),
    PLAY_UPDATE_SCORE(ProtocolState.PLAY, false, 0x56),
    PLAY_UPDATE_SIMULATION_DISTANCE(ProtocolState.PLAY, false, 0x57),
    PLAY_SET_TITLE_SUBTITLE(ProtocolState.PLAY, false, 0x58),
    PLAY_TIME_UPDATE(ProtocolState.PLAY, false, 0x59),
    PLAY_SET_TITLE_TEXT(ProtocolState.PLAY, false, 0x5a),
    PLAY_SET_TITLE_TIMES(ProtocolState.PLAY, false, 0x5b),
    PLAY_ENTITY_SOUNDFX(ProtocolState.PLAY, false, 0x5c),
    PLAY_SOUNDFX(ProtocolState.PLAY, false, 0x5d),
    PLAY_STOP_SOUND(ProtocolState.PLAY, false, 0x5e),
    PLAY_PLAYER_LIST_HEADER_FOOTER(ProtocolState.PLAY, false, 0x5f),
    PLAY_NBT_QUERY_RESPONSE(ProtocolState.PLAY, false, 0x60),
    PLAY_COLLECT_ITEM(ProtocolState.PLAY, false, 0x61),
    PLAY_ENTITY_TELEPORT(ProtocolState.PLAY, false, 0x62),
    PLAY_ADVANCEMENTS(ProtocolState.PLAY, false, 0x63),
    PLAY_ENTITY_PROPERTIES(ProtocolState.PLAY, false, 0x64),
    PLAY_ENTITY_EFFECT(ProtocolState.PLAY, false, 0x65),
    PLAY_DECLARE_RECIPES(ProtocolState.PLAY, false, 0x66),
    PLAY_DECLARE_TAGS(ProtocolState.PLAY, false, 0x67),
    PLAY_TELEPORT_CONFIRM(ProtocolState.PLAY, true, 0x0),
    PLAY_QUERY_BLOCK_NBT(ProtocolState.PLAY, true, 0x1),
    PLAY_SET_DIFFICULTY(ProtocolState.PLAY, true, 0x2),
    PLAY_SEND_CHAT_MESSAGE(ProtocolState.PLAY, true, 0x3),
    PLAY_CLIENT_STATUS(ProtocolState.PLAY, true, 0x4),
    PLAY_CLIENT_SETTINGS(ProtocolState.PLAY, true, 0x5),
    PLAY_REQUEST_TAB_COMPLETE(ProtocolState.PLAY, true, 0x6),
    PLAY_CLICK_WINDOW_BUTTON(ProtocolState.PLAY, true, 0x7),
    PLAY_CLICK_WINDOW(ProtocolState.PLAY, true, 0x8),
    PLAY_CLOSE_WINDOW_NOTIFY(ProtocolState.PLAY, true, 0x9),
    PLAY_PLUGIN_MESSAGE_SERVERBOUND(ProtocolState.PLAY, true, 0xa),
    PLAY_EDIT_BOOK(ProtocolState.PLAY, true, 0xb),
    PLAY_QUERY_ENTITY_NBT(ProtocolState.PLAY, true, 0xc),
    PLAY_INTERACT_ENTITY(ProtocolState.PLAY, true, 0xd),
    PLAY_GENERATE_STRUCTURE(ProtocolState.PLAY, true, 0xe),
    PLAY_KEEP_ALIVE_RESPONSE(ProtocolState.PLAY, true, 0xf),
    PLAY_LOCK_DIFFICULTY(ProtocolState.PLAY, true, 0x10),
    PLAY_PLAYER_POSITION(ProtocolState.PLAY, true, 0x11),
    PLAY_PLAYER_POSITION_AND_ROTATION(ProtocolState.PLAY, true, 0x12),
    PLAY_PLAYER_ROTATION(ProtocolState.PLAY, true, 0x13),
    PLAY_PLAYER_MOVEMENT(ProtocolState.PLAY, true, 0x14),
    PLAY_VEHICLE_MOVE_NOTIFY(ProtocolState.PLAY, true, 0x15),
    PLAY_STEER_BOAT(ProtocolState.PLAY, true, 0x16),
    PLAY_PICK_ITEM(ProtocolState.PLAY, true, 0x17),
    PLAY_CRAFT_RECIPE_REQUEST(ProtocolState.PLAY, true, 0x18),
    PLAY_PLAYER_ABILITIES_REQUEST(ProtocolState.PLAY, true, 0x19),
    PLAY_PLAYER_DIGGING(ProtocolState.PLAY, true, 0x1a),
    PLAY_ENTITY_ACTION(ProtocolState.PLAY, true, 0x1b),
    PLAY_STEER_VEHICLE(ProtocolState.PLAY, true, 0x1c),
    PLAY_PONG(ProtocolState.PLAY, true, 0x1d),
    PLAY_SET_RECIPE_BOOK_STATE(ProtocolState.PLAY, true, 0x1e),
    PLAY_RECIPE_DISPLAYED(ProtocolState.PLAY, true, 0x1f),
    PLAY_NAME_ITEM_STACK(ProtocolState.PLAY, true, 0x20),
    PLAY_RESOURCE_PACK_STATUS(ProtocolState.PLAY, true, 0x21),
    PLAY_ADVANCEMENTS_TAB(ProtocolState.PLAY, true, 0x22),
    PLAY_SELECT_TRADE(ProtocolState.PLAY, true, 0x23),
    PLAY_SET_BEACON_EFFECT(ProtocolState.PLAY, true, 0x24),
    PLAY_SET_HELD_ITEM_SLOT(ProtocolState.PLAY, true, 0x25),
    PLAY_UPDATE_COMMAND_BLOCK(ProtocolState.PLAY, true, 0x26),
    PLAY_UPDATE_COMMAND_BLOCK_MINECART(ProtocolState.PLAY, true, 0x27),
    PLAY_CREATIVE_INVENTORY_ACTION(ProtocolState.PLAY, true, 0x28),
    PLAY_UPDATE_JIGSAW_BLOCK(ProtocolState.PLAY, true, 0x29),
    PLAY_UPDATE_STRUCTURE_BLOCK(ProtocolState.PLAY, true, 0x2a),
    PLAY_UPDATE_SIGN(ProtocolState.PLAY, true, 0x2b),
    PLAY_ANIMATION(ProtocolState.PLAY, true, 0x2c),
    PLAY_SPECTATE(ProtocolState.PLAY, true, 0x2d),
    PLAY_PLAYER_BLOCK_PLACEMENT(ProtocolState.PLAY, true, 0x2e),
    PLAY_USE_ITEM(ProtocolState.PLAY, true, 0x2f);

    companion object {
        fun get(state: ProtocolState, serverbound: Boolean, value: Int): PacketType? {
            return values().firstOrNull {
                it.state == state && it.serverbound == serverbound && it.value == value
            }
        }
    }
}
